oe_webtools_maps.settings:
  type: config_object
  label: 'Webtools Maps Settings'
  mapping:
    map_version:
      type: string
      label: 'Map Version'

field.formatter.settings.oe_webtools_maps_map:
  type: mapping
  label: Webtools Map formatter settings
  mapping:
    show_marker:
      type: boolean
      label: 'Show marker'
    zoom_level:
      type: integer
      label: 'Zoom level'
